=== slaurent22/hk-split-maker/src/schema/silksong/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hksplitmaker.com/silksong/splits.schema.json",
    "title": "SS Splits",
    "description": "A Silksong LiveSplit Configuration",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "names": {
            "additionalProperties": false,
            "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
            "type": "object",
            "properties": {}
        },
        "icons": {
            "additionalProperties": false,
            "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
            "type": "object",
            "properties": {}
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight: Silksong",
                "Hollow Knight: Silksong Category Extensions"
            ]
        },
        "variables": {
            "description": "Additional Info",
            "type": "object"
        },
        "splitIds": {
            "type": "array",
            "items": {
                "oneOf": []
            }
        },
        "offset": {
            "description": "When time should start (formatted like 00:00:00 or 00:00:00.0000000)",
            "type": "string"
        }
    },
    "required": ["categoryName", "gameName", "splitIds"]
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/any.json
{
    "categoryName": "Any%",
    "splitIds": [
        "StartNewGame",
        "MossMother",
        "SilkSpear",
        "BellBeast",
        "SwiftStep",
        "Lace1",
        "DriftersCloak",
        "EnterGreymoor",
        "Moorwing",
        "ClingGrip",
        "Widow",
        "EnterMist",
        "LeaveMist",
        "Phantom",
        "Act2Started",
        "CogworkDancers",
        "Trobbio",
        "Clawline",
        "VaultkeepersMelody",
        "ArchitectsMelody",
        "EnterHighHalls",
        "EnterHighHallsGauntlet",
        "ConductorsMelody",
        "Lace2",
        "EndingSplit"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Any% Glitch": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/all-bellways-mist.json
{
    "categoryName": "All Bellways",
    "splitIds": [
        "Act1Start",
        "MossMotherTrans",
        "SilkSpearTrans",
        "MarrowBell",
        "-SavedFleaDeepDocksSprint",
        "SwiftStepTrans",
        "-DeepDocksStation",
        "-SavedFleaDeepDocksBellway",
        "Lace1Trans",
        "-SavedFleaFarFieldsTrap",
        "DriftersCloakTrans",
        "-FarFieldsStation",
        "-SavedFleaHuntersMarch",
        "-SavedFleaMarrow",
        "-CaravanTroupeGreymoor",
        "-BellhartStation",
        "EnterShellwood",
        "-ShellwoodStation",
        "ClingGripTrans",
        "-Widow",
        "BellhartBell",
        "-GreymoorStation",
        "-EnterSinnersRoad",
        "-EnterBilewater",
        "BilewaterStation",
        "-EnterMist",
        "LeaveMist",
        "-Phantom",
        "-GrandBellwayStation",
        "Act2Started",
        "SlabStation",
        "-EnterMemorium",
        "-EnterPutrifiedDucts",
        "PutrifiedDuctsStation",
        "BlastedStepsStation"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "All Bellways Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/5-tools-ag.json
{
    "categoryName": "5 Tools",
    "splitIds": [
        "StartNewGame",
        "EnterBoneBottom",
        "SwiftStepTrans",
        "WardingBell",
        "Flintslate",
        "FracturedMask",
        "Compass"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "5 Tools Subcategory": "All Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/beer-bottle.json
{
    "categoryName": "Beer Bottle%",
    "splitIds": [
        "StartNewGame",
        "MossMother",
        "SilkSpear",
        "BellBeastTrans",
        "SwiftStep",
        "SavedFleaDeepDocksSprint",
        "SavedFleaDeepDocksBellway",
        "SavedFleaHuntersMarch",
        "BoneBottomSimpleKey",
        "SavedFleaWormways",
        "SavedFleaMarrow",
        "EnterBellhart",
        "Lace1"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Beer Bottle% Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/2-spool-fragments.json
{
    "categoryName": "2 Spool Fragments",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "SilkSpearTrans",
        "SpoolFragment1",
        "MarrowBell",
        "Spool1"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "2 Spool Fragments Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/10-achievements.json
{
    "categoryName": "10 Achievements",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "SilkSpear",
        "MaskShard1",
        "SpoolFragment1",
        "BellBeastTrans",
        "MaskShard2",
        "SwiftStep",
        "Spool1",
        "Lace1Trans",
        "WardingBell",
        "DriftersCloak",
        "MaskShard3",
        "FourthChorus",
        "EnterGreymoor",
        "ReaperCrest",
        "MoorwingTrans",
        "Mask1",
        "ClingGrip",
        "Widow"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "10 Achievements Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/slab-bellbeast.json
{
    "categoryName": "Slab%",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "SilkSpearTrans",
        "BellBeast",
        "SwiftStepTrans",
        "EnterWormways",
        "ClingGripTrans",
        "WardenflyCaptureTrans",
        "SlabKeyIndolent",
        "SlabKeyHeretic",
        "SlabStation"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "Slab% Subcategory": "No Major Glitches",
        "Jail?": "Bellbeast"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/bath-ag.json
{
    "categoryName": "Bath%",
    "splitIds": [
        "StartNewGame",
        "EnterBoneBottom",
        "SwiftStepTrans",
        "EnterBlastedSteps",
        "MaggotsRemoved"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "Bath% Subcategory": "All Glitches"
    }
}
