=== slaurent22/hk-split-maker/src/schema/silksong/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hksplitmaker.com/silksong/splits.schema.json",
    "title": "SS Splits",
    "description": "A Silksong LiveSplit Configuration",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "names": {
            "additionalProperties": false,
            "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
            "type": "object",
            "properties": {}
        },
        "icons": {
            "additionalProperties": false,
            "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
            "type": "object",
            "properties": {}
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight: Silksong",
                "Hollow Knight: Silksong Category Extensions"
            ]
        },
        "variables": {
            "description": "Additional Info",
            "type": "object"
        },
        "splitIds": {
            "type": "array",
            "items": {
                "oneOf": []
            }
        },
        "offset": {
            "description": "When time should start (formatted like 00:00:00 or 00:00:00.0000000)",
            "type": "string"
        }
    },
    "required": ["categoryName", "gameName", "splitIds"]
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/bath.json
{
    "categoryName": "Bath%",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "SilkSpearTrans",
        "MarrowBell",
        "SwiftStep",
        "SavedFleaDeepDocksSprint",
        "Lace1Trans",
        "SavedFleaFarFieldsTrap",
        "DeepDocksStation",
        "SavedFleaDeepDocksBellway",
        "SavedFleaHuntersMarch",
        "SavedFleaMarrow",
        "CaravanTroupeGreymoor",
        "ClingGrip",
        "SavedFleaKratt",
        "MaggotsRemoved"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "Bath% Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/act1-sinner.json
{
    "categoryName": "Act 1",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "SilkSpearTrans",
        "MarrowBell",
        "SwiftStepTrans",
        "EnterWormways",
        "ClingGripTrans",
        "Widow",
        "EnterGreymoor",
        "EnterMist",
        "LeaveMist",
        "Act2Started"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Act 1 Route": "Sinner",
        "Act 1 Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/judgement.json
{
    "categoryName": "Judgement",
    "splitIds": [
        "StartNewGame",
        "MossMother",
        "SilkSpear",
        "BellBeast",
        "MarrowBell",
        "SwiftStep",
        "Lace1",
        "DeepDocksBell",
        "DriftersCloak",
        "GreymoorBell",
        "Moorwing",
        "ClingGrip",
        "Widow",
        "ShellwoodBell",
        "LastJudge",
        "Act2Started"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Judgement Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/judgement-fleas.json
{
    "categoryName": "Judgement",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "SilkSpearTrans",
        "BellBeastTrans",
        "SavedFleaDeepDocksSprint",
        "Lace1Trans",
        "SavedFleaFarFieldsTrap",
        "SavedFleaDeepDocksBellway",
        "SavedFleaHuntersMarch",
        "SavedFleaMarrow",
        "CaravanTroupeGreymoor",
        "GreymoorBell",
        "ClingGrip",
        "Menu",
        "ShellwoodBell",
        "LastJudge",
        "Act2Started"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Judgement Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/act1-judgement-ag.json
{
    "categoryName": "Act 1",
    "splitIds": [
        "StartNewGame",
        "EnterBoneBottom",
        "DeepDocksBell",
        "GreymoorBell",
        "MarrowBell",
        "BellhartBell",
        "ShellwoodBell",
        "LastJudge",
        "Act2Started"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Act 1 Route": "Judgement",
        "Act 1 Subcategory": "All Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/slab-jailed.json
{
    "categoryName": "Slab%",
    "splitIds": [
        "StartNewGame",
        "MossMotherTrans",
        "EnterMosshome",
        "BoneBottomSimpleKey",
        "EnterUpperWormways",
        "EnterShellwood",
        "ClingGripTrans",
        "SwiftStepTrans",
        "WardenflyCaptureTrans",
        "SlabKeyIndolent",
        "SlabKeyHeretic",
        "SlabStation"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "Slab% Subcategory": "No Major Glitches",
        "Jail?": "Jailed"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/all-bellways-bells.json
{
    "categoryName": "All Bellways",
    "splitIds": [
        "Act1Start",
        "MossMotherTrans",
        "SilkSpearTrans",
        "MarrowBell",
        "-SavedFleaDeepDocksSprint",
        "SwiftStepTrans",
        "-DeepDocksStation",
        "-SavedFleaDeepDocksBellway",
        "Lace1Trans",
        "-SavedFleaFarFieldsTrap",
        "DriftersCloakTrans",
        "-FarFieldsStation",
        "GreymoorBell",
        "-SavedFleaHuntersMarch",
        "-SavedFleaMarrow",
        "-CaravanTroupeGreymoor",
        "-BellhartStation",
        "EnterShellwood",
        "-ShellwoodStation",
        "ClingGripTrans",
        "-Widow",
        "BellhartBell",
        "-GreymoorStation",
        "-EnterSinnersRoad",
        "-EnterBilewater",
        "BilewaterStation",
        "-ShellwoodBell",
        "-BlastedStepsStation",
        "Act2Started",
        "-BenchAny",
        "SlabStation",
        "-GrandBellwayStation",
        "EnterMemorium",
        "-EnterPutrifiedDucts",
        "PutrifiedDuctsStation"
    ],
    "gameName": "Hollow Knight: Silksong Category Extensions",
    "variables": {
        "All Bellways Subcategory": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/silksong/categories/act1-judgement.json
{
    "categoryName": "Act 1",
    "splitIds": [
        "StartNewGame",
        "MossMother",
        "SilkSpear",
        "BellBeast",
        "MarrowBell",
        "SwiftStep",
        "Lace1",
        "DeepDocksBell",
        "DriftersCloak",
        "GreymoorBell",
        "Moorwing",
        "ClingGrip",
        "Widow",
        "ShellwoodBell",
        "LastJudge",
        "Act2Started"
    ],
    "gameName": "Hollow Knight: Silksong",
    "variables": {
        "Act 1 Route": "Judgement",
        "Act 1 Subcategory": "No Major Glitches"
    }
}
