=== slaurent22/hk-split-maker/src/schema/splits.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hksplitmaker.com/splits.schema.json",
  "title": "HK Splits",
  "description": "A Hollow Knight LiveSplit Configuration",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "names": {
      "additionalProperties": false,
      "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
      "type": "object",
      "properties": {}
    },
    "icons": {
      "additionalProperties": false,
      "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
      "type": "object",
      "properties": {}
    },
    "ordered": {
      "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
      "type": "boolean"
    },
    "endTriggeringAutosplit": {
      "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
      "type": "boolean"
    },
    "startTriggeringAutosplit": {
      "description": "Autosplit to use to start the timer, rather than starting on new file",
      "enum": []
    },
    "endingSplit": {
      "description": "Info for the last split if it's a game-ending split rather than an autosplit",
      "type": "object",
      "properties": {
        "name": "The name to appear in the LiveSplit UI",
        "icon": "The autosplit name whose icon to use (e.g. RadianceBoss, HollowKnightBoss)"
      }
    },
    "categoryName": {
      "description": "The category name on the associated speedrun.com board.",
      "type": "string"
    },
    "gameName": {
      "description": "The game name on the associated speedrun.com board.",
      "enum": [
        "Hollow Knight",
        "Hollow Knight Category Extensions",
        "Hollow Knight Mods"
      ]
    },
    "variables": {
      "description": "Additional Info",
      "type": "object"
    },
    "splitIds": {
      "type": "array",
      "items": {
        "oneOf": []
      }
    }
  },
  "required": [
    "ordered",
    "endTriggeringAutosplit",
    "categoryName",
    "gameName",
    "splitIds"
  ]
}

=== slaurent22/hk-split-maker/src/asset/categories/gpz.json
{
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "Zote1",
        "MothwingCloak",
        "ShamanStone",
        "MantisClaw",
        "BrettaRescued",
        "DeepnestSpa",
        "Zote2",
        "TramPass",
        "NailUpgrade1",
        "MonarchWings",
        "LittleFool",
        "ZoteKilled",
        "DreamNail",
        "GreyPrince"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "GPZ%"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/low-ag.json
{
  "categoryName": "Low%",
  "splitIds": [
    "KingsPass",
    "DreamNail",
    "Dreamer1",
    "Dreamer2",
    "Dreamer3",
    "UnchainedHollowKnight"
  ],
  "ordered": true,
  "endTriggeringAutosplit": false,
  "endingSplit": {
    "name": "Hollow Knight",
    "icon": "HollowKnightBoss"
  },
  "gameName": "Hollow Knight",
  "variables": {
    "Low% Glitch": "All Glitches"
  }
}

=== slaurent22/hk-split-maker/src/asset/categories/grass.json
{
    "splitIds": [
        "Dirtmouth",
        "AspidHunter",
        "CrossroadsStation",
        "FalseKnight",
        "VengefulSpirit",
        "Greenpath",
        "MossKnight",
        "MothwingCloak",
        "GruzMother",
        "BlueLake",
        "DreamNail",
        "RestingGroundsStation",
        "ElderHu",
        "MantisClaw",
        "Xero",
        "KingsStationStation",
        "SpiritGladeOpen",
        "GorgeousHusk",
        "Lemm2",
        "LumaflyLantern",
        "CrystalPeak",
        "SlyKey",
        "CrystalHeart",
        "ElegantKey",
        "TollBenchCity",
        "ShadeSoul",
        "DesolateDive",
        "SoulTyrant",
        "TollBenchBasin",
        "BrokenVessel",
        "MonarchWings",
        "LostKin",
        "HiddenStationStation",
        "FailedKnight",
        "DreamGate",
        "KingdomsEdge",
        "Hornet2",
        "KingsBrand",
        "ShadeCloak",
        "Markoth",
        "FogCanyon",
        "TeachersArchive",
        "NoEyes",
        "MegaMossCharger",
        "HowlingWraiths",
        "QueensGardensStation",
        "Marmu",
        "TraitorLord",
        "DreamNail2",
        "WhitePalace",
        "Godhome"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "All Grass",
        "icon": "TreeCity"
    },
    "gameName": "Hollow Knight Mods",
    "categoryName": "Grass%"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/spelless-dreamshield.json
{
  "categoryName": "Spelless",
  "splitIds": [
    "SlyRescued",
    "FalseKnight",
    "LumaflyLantern",
    "Dreamshield",
    "EnterGreenpath",
    "MothwingCloak",
    "MegaMossCharger",
    "FragileStrength",
    "MantisClaw",
    "CrystalHeart",
    "GorgeousHusk",
    "NailUpgrade1",
    "BlackKnight",
    "FogCanyonEntry",
    "Uumuu",
    "SporeShroom",
    "BeastsDenTrapBench",
    "Hegemol"
  ],
  "ordered": true,
  "endTriggeringAutosplit": false,
  "endingSplit": {
    "name": "Hollow Knight",
    "icon": "HollowKnightBoss"
  },
  "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/5-mimics.json
{
  "categoryName": "5 Mimics",
  "splitIds": [
    "VengefulSpirit",
    "EnterGreenpath",
    "MothwingCloak",
    "MantisClaw",
    "Mimic3",
    "BlueLake",
    "Lemm2",
    "CrystalHeart",
    "Mimic4",
    "LittleFool",
    "ColosseumBronze",
    "Mimic5"
  ],
  "ordered": true,
  "endTriggeringAutosplit": true,
  "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/categories/fool-1221.json
{
    "categoryName": "Fool%",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "NotchShrumalOgres",
        "MantisClaw",
        "CycloneSlash",
        "BlueLake",
        "GorgeousHusk",
        "DashSlash",
        "NailUpgrade1",
        "ShadeSoul",
        "SpellTwister",
        "LittleFool",
        "ColosseumBronze",
        "ColosseumSilver",
        "ColosseumGold"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/3vf-stag-nest.json
{
    "categoryName": "3 Vessel Fragments",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "VesselFragment1",
        "VesselFragment2",
        "Vessel1"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/te-flukamoth.json
{
  "categoryName": "True Ending",
  "splitIds": [
    "FuryOfTheFallen",
    "VengefulSpirit",
    "SoulCatcher",
    "MothwingCloak",
    "NotchShrumalOgres",
    "TransClaw",
    "Lemm2",
    "SpellTwister",
    "DesolateDive",
    "StoreroomsStation",
    "SlyKey",
    "CrystalHeart",
    "DreamNail",
    "Dreamshield",
    "NotchSalubra1",
    "ElegantKey",
    "EnterSanctumWithShadeSoul",
    "SoulTyrantEssence",
    "Flukenest",
    "BrokenVessel",
    "LostKinEssence",
    "FailedChampionEssence",
    "DreamGate",
    "KingsStationStation",
    "KingsBrand",
    "ShadeCloak",
    "Markoth",
    "Lurien",
    "LumaflyLantern",
    "Monomon",
    "NoEyesEssence",
    "TollBenchQG",
    "MarmuEssence",
    "WhiteFragmentLeft",
    "GalienEssence",
    "Hegemol",
    "WhitePalaceEntry",
    "Kingsoul",
    "VoidHeart",
    "HollowKnightDreamnail"
  ],
  "ordered": true,
  "endTriggeringAutosplit": false,
  "endingSplit": {
    "name": "Radiance",
    "icon": "RadianceBoss"
  },
  "gameName": "Hollow Knight"
}
