=== slaurent22/hk-split-maker/src/schema/splits.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hksplitmaker.com/splits.schema.json",
  "title": "HK Splits",
  "description": "A Hollow Knight LiveSplit Configuration",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "names": {
      "additionalProperties": false,
      "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
      "type": "object",
      "properties": {}
    },
    "icons": {
      "additionalProperties": false,
      "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
      "type": "object",
      "properties": {}
    },
    "ordered": {
      "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
      "type": "boolean"
    },
    "endTriggeringAutosplit": {
      "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
      "type": "boolean"
    },
    "startTriggeringAutosplit": {
      "description": "Autosplit to use to start the timer, rather than starting on new file",
      "enum": []
    },
    "endingSplit": {
      "description": "Info for the last split if it's a game-ending split rather than an autosplit",
      "type": "object",
      "properties": {
        "name": "The name to appear in the LiveSplit UI",
        "icon": "The autosplit name whose icon to use (e.g. RadianceBoss, HollowKnightBoss)"
      }
    },
    "categoryName": {
      "description": "The category name on the associated speedrun.com board.",
      "type": "string"
    },
    "gameName": {
      "description": "The game name on the associated speedrun.com board.",
      "enum": [
        "Hollow Knight",
        "Hollow Knight Category Extensions",
        "Hollow Knight Mods"
      ]
    },
    "variables": {
      "description": "Additional Info",
      "type": "object"
    },
    "splitIds": {
      "type": "array",
      "items": {
        "oneOf": []
      }
    }
  },
  "required": [
    "ordered",
    "endTriggeringAutosplit",
    "categoryName",
    "gameName",
    "splitIds"
  ]
}

=== slaurent22/hk-split-maker/src/asset/categories/eternal-ordeal-1mg.json
{
    "categoryName": "Eternal Ordeal% 1mg",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "EnterSanctum",
        "DesolateDive",
        "CrystalHeart",
        "DreamNail",
        "ShadeSoul",
        "MonarchWings",
        "Flukenest",
        "EternalOrdealUnlocked",
        "EternalOrdealAchieved"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/categories/enraged-guardian.json
{
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "GruzMother",
        "GorgeousHusk",
        "LumaflyLantern",
        "CrystalGuardian1",
        "CrystalGuardian2"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Enraged Guardian%"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/lbc.json
{
  "categoryName": "Lifeblood Core%",
  "splitIds": [
    "VengefulSpirit",
    "EnterGreenpath",
    "MothwingCloak",
    "MantisClaw",
    "BlueLake",
    "GorgeousHusk",
    "JonisBlessing",
    "KingsBrand",
    "LifebloodCore"
  ],
  "ordered": true,
  "endTriggeringAutosplit": true,
  "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/spelless-low.json
{
  "categoryName": "Low% Spelless",
  "splitIds": [
    "GruzMother",
    "Mask1",
    "DreamNail",
    "MantisClaw",
    "Hegemol",
    "BlackKnight",
    "Lurien",
    "CrystalHeart",
    "Uumuu",
    "Monomon"
  ],
  "ordered": true,
  "endTriggeringAutosplit": false,
  "endingSplit": {
    "name": "Hollow Knight",
    "icon": "HollowKnightBoss"
  },
  "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/categories/p1.json
{
    "categoryName": "Pantheon of the Master",
    "splitIds": [
        "VengeflyKingP",
        "GruzMotherP",
        "FalseKnightP",
        "MassiveMossChargerP",
        "Hornet1P",
        "GorbP",
        "DungDefenderP",
        "SoulWarriorP",
        "BroodingMawlekP",
        "OroMatoNailBrosP"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight"
}

=== slaurent22/hk-split-maker/src/asset/categories/all-unbreakable-charms.json
{
    "splitIds": [
        "VengefulSpirit",
        "MothwingCloak",
        "MantisClaw",
        "MantisLords",
        "GruzMother",
        "DreamNail",
        "FragileStrength",
        "Gorb",
        "Xero",
        "KingdomsEdge",
        "KingsStationStation",
        "GorgeousHusk",
        "BlackKnight",
        "Lemm2"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "All Unbreakable Charms"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/shriek.json
{
  "categoryName": "Shriek%",
  "splitIds": [
    "VengefulSpirit",
    "EnterGreenpath",
    "MothwingCloak",
    "MantisClaw",
    "HowlingWraiths",
    "BlueLake",
    "KingdomsEdgeEntry",
    "KingsBrand",
    "BasinEntry",
    "AbyssShriek"
  ],
  "ordered": true,
  "endTriggeringAutosplit": true,
  "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/categories/nice-1221.json
{
    "categoryName": "Nice%",
    "splitIds": [
        "FuryOfTheFallen",
        "VengefulSpirit",
        "SoulCatcher",
        "MothwingCloak",
        "MantisClaw",
        "MantisLords",
        "MarkOfPride",
        "Dashmaster",
        "GruzMother",
        "ShamanStone",
        "DashSlash",
        "ShadeSoul",
        "SpellTwister",
        "DesolateDive",
        "CrystalHeart",
        "DescendingDark",
        "DreamNail",
        "Dreamshield",
        "Lurien",
        "Flukenest",
        "DefendersCrest",
        "IsmasTear",
        "MonarchWings",
        "KingsBrand",
        "CycloneSlash",
        "Gorb",
        "JonisBlessing",
        "BaldurShell",
        "GreatSlash",
        "ThornsOfAgony",
        "NailmastersGlory",
        "WaywardCompass",
        "Grubsong",
        "Mask1",
        "FragileStrength",
        "ElderHu",
        "Monomon",
        "HowlingWraiths",
        "Hegemol",
        "Xero",
        "SoulEater",
        "QuickFocus",
        "ShadeCloak",
        "AbyssShriek"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight Category Extensions"
}
