=== slaurent22/hk-split-maker/src/schema/splits.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://hksplitmaker.com/splits.schema.json",
  "title": "HK Splits",
  "description": "A Hollow Knight LiveSplit Configuration",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "names": {
      "additionalProperties": false,
      "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
      "type": "object",
      "properties": {}
    },
    "icons": {
      "additionalProperties": false,
      "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
      "type": "object",
      "properties": {}
    },
    "ordered": {
      "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
      "type": "boolean"
    },
    "endTriggeringAutosplit": {
      "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
      "type": "boolean"
    },
    "startTriggeringAutosplit": {
      "description": "Autosplit to use to start the timer, rather than starting on new file",
      "enum": []
    },
    "endingSplit": {
      "description": "Info for the last split if it's a game-ending split rather than an autosplit",
      "type": "object",
      "properties": {
        "name": "The name to appear in the LiveSplit UI",
        "icon": "The autosplit name whose icon to use (e.g. RadianceBoss, HollowKnightBoss)"
      }
    },
    "categoryName": {
      "description": "The category name on the associated speedrun.com board.",
      "type": "string"
    },
    "gameName": {
      "description": "The game name on the associated speedrun.com board.",
      "enum": [
        "Hollow Knight",
        "Hollow Knight Category Extensions",
        "Hollow Knight Mods"
      ]
    },
    "variables": {
      "description": "Additional Info",
      "type": "object"
    },
    "splitIds": {
      "type": "array",
      "items": {
        "oneOf": []
      }
    }
  },
  "required": [
    "ordered",
    "endTriggeringAutosplit",
    "categoryName",
    "gameName",
    "splitIds"
  ]
}

=== slaurent22/hk-split-maker/src/asset/categories/any_cp.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "GruzMother",
        "DreamNail",
        "WatcherChandelier",
        "BlackKnight",
        "LumaflyLantern",
        "CrystalHeart",
        "Uumuu",
        "QueensGardens",
        "BeastsDenTrapBench",
        "Hegemol"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight",
    "categoryName": "Any%",
    "variables": {
        "platform": "PC",
        "patch": "1.5.75.11827"
    }
}

=== slaurent22/hk-split-maker/src/asset/categories/happy-couple-1221.json
{
    "categoryName": "Happy Couple",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "GreenpathStation",
        "MothwingCloak",
        "Grub1",
        "MantisClaw",
        "Grub2",
        "Grub3",
        "BlueLake",
        "GorgeousHusk",
        "Grub4",
        "Grub5",
        "DashSlash",
        "Grub6",
        "ShadeSoul",
        "DesolateDive",
        "Grub7",
        "Grub8",
        "KingsStationStation",
        "Grub9",
        "Grub10",
        "CrystalHeart",
        "Grub11",
        "Grub12",
        "Grub13",
        "Grub14",
        "DescendingDark",
        "DreamNail",
        "Grub15",
        "Grub16",
        "Grub17",
        "Grub18",
        "Grub19",
        "Grub20",
        "Grub21",
        "Ore1",
        "Grub22",
        "TramPass",
        "Grub23",
        "Ore2",
        "MonarchWings",
        "LostKin",
        "Grub24",
        "Grub25",
        "Grub26",
        "Grub27",
        "LittleFool",
        "ColosseumBronze",
        "ColosseumSilver",
        "Grub28",
        "Grub29",
        "Grub30",
        "Grub31",
        "Ore4",
        "Ore5",
        "Ore6",
        "NailUpgrade4",
        "GreatSlash",
        "HappyCouplePlayerDataEvent"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "variables": {
        "glitch": "No Major Glitches"
    }
}

=== slaurent22/hk-split-maker/src/asset/categories/elegy.json
{
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "GreenpathStation",
        "MothwingCloak",
        "MantisClaw",
        "EnterSanctum",
        "DesolateDive",
        "GrubCitySanctum",
        "GrubCrossroadsGuarded",
        "GrubCrystalPeaksSpikes",
        "CrystalHeart",
        "GrubCrystalPeaksCrystalHeart",
        "GrubCrystalPeaksCrushers",
        "GrubCrystalPeaksBottomLever",
        "GrubCrystalPeaksMound",
        "DescendingDark",
        "DreamNail",
        "GrubRestingGroundsCrypts",
        "ShamanStone",
        "GrubCrossroadsSpikes",
        "GrubCrossroadsWall",
        "GrubCityBelowSanctum",
        "GrubWaterwaysCenter",
        "GrubWaterwaysIsma",
        "GrubFungalBouncy",
        "GrubFungalSporeShroom",
        "GrubDeepnestMimics",
        "GrubDeepnestNosk",
        "GrubDeepnestSpikes",
        "TramPass",
        "GrubBasinDive",
        "MonarchWings",
        "GrubBasinWings",
        "GrubHiveInternal",
        "GrubWaterwaysHwurmps",
        "GrubHiveExternal",
        "GrubKingdomsEdgeOro",
        "GrubKingdomsEdgeCenter",
        "GrubCityBelowLoveTower",
        "GrubCityGuardHouse",
        "GrubCitySpire",
        "GrubCrystalPeaksMimics",
        "GrubCrystalPeaksCrown",
        "GrubCrossroadsVengefly",
        "GrubCrossroadsAcid",
        "GrubFogCanyonArchives",
        "LoveKey",
        "GrubQueensGardensBelowStag",
        "GrubQueensGardensUpper",
        "GrubQueensGardensWhiteLady",
        "GrubDeepnestDark",
        "GrubDeepnestBeastsDen",
        "GrubGreenpathMossKnight",
        "GrubCliffsBaldurShell",
        "GrubGreenpathHunter",
        "GrubGreenpathCornifer",
        "GrubGreenpathVesselFragment",
        "Collector",
        "GrubberflysElegy"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Elegy%"
}

=== slaurent22/hk-split-maker/src/asset/categories/aluba.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "Aluba"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Aluba%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/all-skills.json
{
  "categoryName": "All Skills",
  "splitIds": [
    "VengefulSpirit",
    "EnterGreenpath",
    "MothwingCloak",
    "MenuClaw",
    "BlueLake",
    "MenuGorgeousHusk",
    "DashSlash",
    "ShadeSoul",
    "DesolateDive",
    "KingsStationStation",
    "CrystalHeart",
    "DescendingDark",
    "DreamNail",
    "Lurien",
    "BasinEntry",
    "MonarchWings",
    "KingsBrand",
    "CycloneSlash",
    "Monomon",
    "GreatSlash",
    "HowlingWraiths",
    "Hegemol",
    "ShadeCloak",
    "AbyssShriek",
    "UnchainedHollowKnight"
  ],
  "ordered": true,
  "endTriggeringAutosplit": false,
  "endingSplit": {
    "name": "Hollow Knight",
    "icon": "HollowKnightBoss"
  },
  "gameName": "Hollow Knight",
  "variables": {
    "All Skills Glitch": "No Major Glitches"
  }
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/p4.json
{
  "categoryName": "Pantheon of the Knight",
  "splitIds": [
    "EnragedGuardianP",
    "LostKinP",
    "NoEyesP",
    "TraitorLordP",
    "WhiteDefenderP",
    "FailedChampionP",
    "MarkothP",
    "WatcherKnightsP",
    "SoulTyrantP",
    "PureVesselP"
  ],
  "ordered": true,
  "endTriggeringAutosplit": true,
  "gameName": "Hollow Knight"
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/pop-percent.json
{
  "categoryName": "PoP%",
  "splitIds": [
    "VengefulSpirit",
    "EnterGreenpath",
    "MothwingCloak",
    "BlueLake",
    "DreamNail",
    "ElderHuEssence",
    "MantisClaw",
    "GalienEssence",
    "XeroEssence",
    "GorgeousHusk",
    "LumaflyLantern",
    "SlyKey",
    "CrystalHeart",
    "ShadeSoul",
    "DesolateDive",
    "SoulTyrantEssence",
    "TollBenchBasin",
    "BrokenVessel",
    "MonarchWings",
    "DreamGate",
    "FailedChampionEssence",
    "GorbEssence",
    "NoEyesEssence",
    "WhitePalaceEntry",
    "PathOfPainEntry",
    "PathOfPain"
  ],
  "ordered": true,
  "endTriggeringAutosplit": true,
  "gameName": "Hollow Knight Category Extensions"
}

=== slaurent22/hk-split-maker/src/asset/categories/spelless-te.json
{
    "splitIds": [
        "FuryOfTheFallen",
        "FalseKnight",
        "Longnail",
        "EnterGreenpath",
        "MothwingCloak",
        "MegaMossCharger",
        "MantisClaw",
        "DreamNail",
        "ElderHu",
        "SporeShroom",
        "Galien",
        "Xero",
        "NailUpgrade2",
        "LumaflyLantern",
        "CrystalHeart",
        "TollBenchBasin",
        "BrokenVessel",
        "MonarchWings",
        "Gorb",
        "DreamGate",
        "KingsBrand",
        "ShadeCloak",
        "Markoth",
        "BlackKnight",
        "FailedKnight",
        "Uumuu",
        "NoEyes",
        "Marmu",
        "TraitorLord",
        "Hegemol",
        "DreamNail2",
        "Kingsoul",
        "VoidHeart",
        "HollowKnightDreamnail"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "HollowKnight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Spelless True Ending"
}
